# Generated by Django 2.1 on 2020-05-13 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='photp',
            new_name='photo',
        ),
    ]
